apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee-service-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: digambergupta/employee-service
        ports:
        - name: service-port
          containerPort: 8080