apiVersion: v1
kind: Pod
metadata:
  name: employee-service.com
  labels:
    app: employee-service
spec:
  containers:
  - name: employee-service
    image: digambergupta/employee-service
    ports:
    - name: service-port
      containerPort: 8080
