apiVersion: v1
kind: ReplicationController
metadata:
  name: employee-service-controller
spec:
  replicas: 4
  selector:
    app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: digambergupta/employee-service
        ports:
        - name: service-port
          containerPort: 3000